### ISSUE TITLE
Investigate use and role of ngram matching and Apache Lucene in improving geocoder parser

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#119]

**Comment by mraross** [comment]
There might be a simple and powerful way to incorporate Lucene into the geocoder. We could use field-based matching on the full input string in deep-matching as follows:

if the regular parser fails to provide a good match (e.g., 90 or above) then
   use Lucene to find the best field-based match on the full input string
   run best field-based match through the regular parser
   if resulting best match scores ninety-five or higher
      add a five-point penalty for noise words (NOISE_WORDS.ignored) and return best match along with other lesser matches
   else
      return just best matches found by regular parser
   endif
endif

**Comment by cmhodgson** [comment]
What does:

**Comment by mraross** [comment]
As discussed in our phone chat this morning, in deep matching, we could use a bi-gram matcher to match the full input address string against fullAddress of all reference civic and non-civic addresses. We could encode number fields as number token strings (e.g., "~n") in both input and reference addresses to allow any number to match in numeric fields like civicNumber and unitNumber. Brian could experiment with this approach in python.

**Comment by mraross** [comment]
The [Ngram similarity matcher](http://www.cs.ualberta.ca/~kondrak/papers/spire05.pdf) defines and uses the nsim similarity metric which takes n-gram order and string length into account when computing best match.

[Here](ftp://ftp.netapp.com/frm-ntap/opensource/Active_IQ_Performance_Analytics_Services/2.0/opensource_packages/jar_sources/lucene-suggest-5.5.4.jar/org/apache/lucene/search/spell/NGramDistance.java) is the Lucene Java implementation of Nsim.

https://lucene.apache.org/core/2_9_4/api/contrib-spellchecker/org/apache/lucene/search/spell/NGramDistance.html

**Comment by mraross** [comment]
Lucene implements N-DIST in Java

ftp://ftp.netapp.com/frm-ntap/opensource/Active_IQ_Performance_Analytics_Services/2.0/opensource_packages/jar_sources/lucene-suggest-5.5.4.jar/org/apache/lucene/search/spell/NGramDistance.java

https://lucene.apache.org/core/2_9_4/api/contrib-spellchecker/org/apache/lucene/search/spell/NGramDistance.html

**Comment by cmhodgson** [comment]
lucene-spellchecker v3.6.2 (https://mvnrepository.com/artifact/org.apache.lucene/lucene-spellchecker/3.6.2) from 2012 is the most recent version of this code that I can find, Lucene now at v8.6.3 no longer has the ngramdistance class. I can't see any reference ever of any way to build an index to find the closest match from a large collection addresses/documents/etc, the ngramdistance class just calculates the metric between two strings. Just having a metric doesn't allow us to find the best match from millions of references... is there a paper showing how to build an index using this metric?

**Comment by cmhodgson** [comment]
Here is the ngramdistance class in the latest version of lucene-suggest v8.6.3:
https://lucene.apache.org/core/8_6_3/suggest/org/apache/lucene/search/spell/NGramDistance.html
Maybe we have to spell check/correct our input first before doing our parsing? (using Lucene's spellchecker?) This could deal with misplaced spaces and typos, but still doesn't help with glued and unglued words...

**Comment by mraross** [comment]
Isn't the inverted index one entry per bigram with each entry holding a bigram value and a sequence of all site ids that contain that bigram?

**Comment by cmhodgson** [comment]
How would the standard bi-gram index find things that are closer via the n-dist similarity metric? For the exact reasons in the paper for n-grams being a bad similarity metric on their own, using the standard n-gram based index has the potential to find a lot of bad matches (according to the n-dist metric) before it gets to the good ones...

**Comment by cmhodgson** [comment]
I tried two different approaches to test the effectiveness of using Lucence-based matching for the geocoder:

1) implemented a basic "one big string" matcher geocoder which simply added all civic number sites to a lucene index and then queried it using test addresses. This made clear the biggest issue with using lucene, any kind of street/locality/ aliases or abbreviations were not able to be used effectively. The seemly best way to try to use them required adding additional addresses for each alias/abbreviation, so that all possibly forms of an address were enumerated in the index, which caused the index to get quite large, and still didn't have great performance. We also had the problem that it was impossible to score the results in a meaningful way as the structure of the input was unknown and thus very difficult to compare with the resulting matches. 

2) implemented a "wordmap" which is the data structure previously implemented using a trie, to map input words to possible interpretations, using a lucene index instead of a trie. This didn't have as good of performance, and didn't actually solve the problems that we hoped to solve using lucene and n-grams, namely, terrible misspellings and misplaced spaces. 

Overall, we decided that if a lucene or n-gram based approach was viable, it would require too extensive changes to our architecture to be easily implemented, and that it didn't offer enough of a potential improvement to warrant the effort. For now we will explore alternative, incremental parser changes.

**Comment by alixcote** [comment]
Based on Chris' recommendation, we will close this and work on incremental changes instead.

From comment above:
_Overall, we decided that if a lucene or n-gram based approach was viable, it would require too extensive changes to our architecture to be easily implemented, and that it didn't offer enough of a potential improvement to warrant the effort. For now we will explore alternative, incremental parser changes._
