### ISSUE TITLE
Second word of a streetName not spell-corrected

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#121]
The following address contains a two-word streetName:

     2386 Troy Ann Way, Nanaimo, BC

The first word  (e.g., Troy) is spelled correctly; the second word isn't (e.g., should be Anne). Submitting this address as folllows:

https://geocoder.api.gov.bc.ca/addresses.html?locationDescriptor=parcelPoint&echo=true&addressString=2386+Troy+Ann+Way%2C+Nanaimo%2C+BC

yields faults unrecognized.notAllowed and streetName.partialMatch faults for a score of 66. However, if just the first word is spelled wrong as follows:

https://geocoder.api.gov.bc.ca/addresses.html?locationDescriptor=parcelPoint&echo=true&addressString=2386+Troye+Anne+Way%2C+Nanaimo%2C+BC

the geocoder corrects spelling of first word and gives just a streetName.partialMatch fault and a score of 98.

The geocoder should be able to spell correct words in a name other than the first.

**Comment by mraross** [comment]
Here's a counter-example where the geocoder spell-corrected the second word in both the streetName and localityName:

     705 Canada Gaimes Way, Prince Gorge, BC

https://geocoder.api.gov.bc.ca/addresses.html?locationDescriptor=parcelPoint&echo=true&addressString=705+Canada+Gams+Way%2C+Prince+Gorge%2C+BC

The geocoder gives streetName.spelledWrong and localityName.spelledWrong faults and a score of 96. Go figure!

**Comment by cmhodgson** [comment]
I suspect this is because "Ann" is already a correct spelling of a word in a street name. I can't recall exactly what is happening but we definitely match already-correct words with a higher preference than spell-corrected alternatives. And the correction currently happens on the word level, not the street name body or full street name level.

**Comment by gleeming** [comment]
If I recall, we coded in a 3-character limit for attempting spelling corrections to prevent a bunch of similar small words from being accepted?  Perhaps this logic is working against us here and should be eliminated in cases of multi-word name bodies.

Adding a character works fine, e.g. 
https://geocoder.api.gov.bc.ca/addresses.html?locationDescriptor=parcelPoint&echo=true&addressString=2386+Troy+Annie+Way%2C+Nanaimo%2C+BC

But removing one from Troy to Tro puts it at 3-characters and results in a score of 23
https://geocoder.api.gov.bc.ca/addresses.html?locationDescriptor=parcelPoint&echo=true&addressString=2386+Tro+Anne+Way%2C+Nanaimo%2C+BC

**Comment by alixcote** [comment]
Result is now 90 instead of 66. We can close this as we have seen an improvement and the correct address is returned.

https://geocoder.api.gov.bc.ca/addresses.html?locationDescriptor=parcelPoint&echo=true&addressString=2386+Troy+Ann+Way%2C+Nanaimo%2C+BC

**Comment by cmhodgson** [comment]
I was thinking the same thing too, although what bothered me was more that the input includes the street type "Way" but the match is given a 6 point penalty for not including it, because it has to get thrown out with the "locality garbage" because that has to come exactly before the locality. However I don't have a great fix for that, and this is already a decent result.

The actual problem this ticket was identifying was not about spell-correcting second words, but short words. As Graeme mentioned above, we presently don't spell correct words of 3 characters or less because they tend to have too many matches which make for worse results and slows down the geocoding process considerably. The spell-correction has to be done on each word, because until we have the spell corrected version, we don't even know if the word IS a street name or not. For now I'm happy to have this ticket closed.
