### ISSUE TITLE
In Test, geocoder admin app, config data is disappearing after entering new abbreviations and one unit designator

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#126]
In geocoder admin app located at:

https://ols-geocoder-admin-test.pathfinder.gov.bc.ca/params.jsp

I entered the abbreviations specified in https://github.com/bcgov/ols-geocoder/issues/102

I also added the unit Designator HOUSE.

I then exported the config and tried to validate it. The comparison was wonky. Almost all locality mappings were dropped in the live version and the file has more abbreviations than the live version.

**Comment by cmhodgson** [comment]
Dave, is that instance of the geocoder admin app backed by cassandra or by the file config? I think we should start by confirming that what is shown on the admin app matches the contents of the back-end config storage.

**Comment by dkelsey** [comment]
it is using cassandra and not the file based config.
I'll look into it during work hours.
I'll find out what Michael is doing.

**Comment by mraross** [comment]
Prod version has different file base properties than test version. Here's prod version:

![image](https://user-images.githubusercontent.com/11318574/93572735-1cd7f580-f94b-11ea-9833-17bf9ed6c094.png)

and here is  test version:

![image](https://user-images.githubusercontent.com/11318574/93572959-6de7e980-f94b-11ea-8d2d-a26d09ddfd8a.png)

**Comment by cmhodgson** [comment]
The dataSource.baseFileUrl.* are old parameters that are no longer used. I have not yet implemented anything to clean up those old parameters, partly due to wanting to keep the ability to roll back to previous versions. They are being ignored and should not be of concern.

Dave, Michael demonstrated the issues he was having, and I have reason to believe that the code that reads and writes the configuration parameters to cassandra may not be consistently reliable - but I have not been able to replicate the exact problems he is having, on my own setup locally.

**Comment by dkelsey** [comment]
Yes, that's correct.

In PROD the different baseFile variables are an artifact of older installs of the admin app.  Each version of the admin app uses different variables.   This is so we can move back and forth with versions of the admin app.  Because the cassandra cluster in PROD operated through all the versions of the admin app, it has persisted the data over time.

in contrast, I setup the TEST env just a while ago, with a new cassandra cluster; so you will only see the settings the current version of the admin app would have persisted.

**Comment by dkelsey** [comment]
@cmhodgson I'll work on reproducing the issue Michael describes.  I recall something similar when I set it up. we were in such a rush that it did not get addressed.

**Comment by cmhodgson** [comment]
Dave would it possible for me to connect to your test cassandra instance from my desktop, through VPN? I would like to be able to either directly query it with cqlsh and/or connect my locally-running (debuggable) admin app to your server to see if I can replicate the issues that way.

**Comment by cmhodgson** [comment]
The known problems with the admin app are fixed and delivered in ols-util:1.1.1, ols-geocoder:4.0.3, and ols-geocoder-cpf-plugin:4.0.3.
Dave also found that there was problems with the synchronization of the Cassandra servers in the test environment, which were exacerbating this issue.

**Comment by BK01** [comment]
Validated in Geocoder 4.1-Gold (DLV)
