### ISSUE TITLE
Add support for an adminAreas property in geocoder address responses 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#138]
adminAreas is a list of name,value pairs where name represents the name of a set of admin areas (e.g., CHSA), and value is a valid name or code of an admin area within the set. In CSV format, adminAreas could be a single string containing name-value pairs separated by commas (e.g., "set_name1,admin_area1,set_name2,admin_area2")

Admin areas could be computed once at data prep time in Geocodable BC Maker using the address point location provided by address authorities.

**Comment by mraross** [comment]
Determining the admin area of a given site are straightforward. Determining admin area for a given locality is a bit trickier since we are really talking about a polygon in polygon test.  I propose that, at data integration time,  we perform the polygon in polygon test for every DRA locality and output a new table of localities that map to multiple admin areas. For example:

|adminAreaType|locality|
|---|---|---|
Electoral District|Victoria
Electoral District|Vancouver
CHSA|Vancouver

These entries mean Victoria and Vancouver are associated with more than one Electoral District and Vancouver is associated with more than one CHSA.  This table can be then be used further down the data integration pipeline to populate the admin areas list for a given locality. Vancouver's CHSA admin code would be set to <many> (e.g., "*"). Applications would then know that a locality doesn't have a single associated CHSA and can act appropriately.


We could also determine the admin areas of BCGNIS localities that are not DRA localities using the BCGNIS locality point.  In other words, if the point is actually outside the village, it may be in an adjacent locality. This is a separate data quality issue that we may be able to help Heritage Branch with.

**Comment by mraross** [comment]
The geocoder should also compute admin areas of interpolated addresses where possible using the admin area values of bounding, known addresses and anchor points.

**Comment by cmhodgson** [comment]
Note that this implies we need to store the admin area values for the endpoints of each segment, in order to interpolate between the ends of the segment and the first and last access points (or if the segment has no APs, to interpolate between the ends).

**Comment by gleeming** [comment]
Also a comment on the polygon-in-polygon test previously mentioned to map locality with admin area.  The original concept we considered was for sites only, and when a locality match precision solution was requested we discussed going with a simple point in polygon test.  This could be done exclusively within the BAARG since the JSON locality input into that app is reduced to a point feature.  To do a full poly compare solution would require a more involved approach, e.g.
a) including all admin area files as inputs to both FME and BAARG so that FME could do the locality calc and BAARG the sites (instead of just admin inputs to BAARG only and having it do the point-based computations for all outputs)
b) having FME output a new locality polygon geometry file to be used as an additional input for the BAARG calculations

**Comment by alixcote** [comment]
Close - don't want to pre-calculate admin area and not scalable. MAPs GeoServer could be an option.
