### ISSUE TITLE
In Test, batch geocoder fails to load when configured to talk to Cassandra in Test

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#205]

**Comment by cmhodgson** [comment]
I think what is happening is that the cassandra drivers are trying to load the default configuration values from a file (typesafe is a library for configurations). The file that it wants is in one of the cassandra jar files. The problem is that it tries to use a classloader to find the file, but the classloader that it is using is not the same one that loaded the cassandra jar, likely because of how the CPF dynamically loads classes using the maven poms to find dependencies to load. I actually had a similar problem with this because the code that was loading the default cassandra config was in the ols-geocoder maven package, but it was the ols-util maven package that had the dependency on the cassandra drivers. It might even be my fix for that (specifying a different classloader to use) that is causing this problem, or at least exacerbating it. I will see if there is another way to implement my fix, or if it is even necessary anymore, and commit a change, which you can try to see if it works in CPF.

**Comment by cmhodgson** [comment]
Here is my attempted fix, in ols-util: https://github.com/bcgov/ols-util/pull/13

**Comment by mraross** [comment]
Abandoned Cassandra for file-based configuration data in batch geocoder. Verified in production.
