### ISSUE TITLE
Ensure generated accessPoints border parcel frontage on named street

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#207]
When  6225 216 St in Langley is geocoded as a parcelPoint, the marker is being placed at the centroid, I believe (blue marker below) which is fine.

When the same address is geocoded as an accessPoint  (green marker) it’s not placing the marker at the access point or the parcel.  I have marked the access point in red on the screenshot below.

![accesspoint.jpg](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/4811c6c2-b895-4425-ad7b-0f7f37e3b32d)

**Comment by gleeming** [comment]
If not supplied by a custodian, access points in geocoder are currently generated in the BAARG based on relative positioning of parcel points (centroids).  The APs can end up shifted several blocks away from the parcel and even flipped to the other side of a segment in order to resolve data inconsistencies such as mixed parity, non-monotonic progression, range overlaps, etc.  Since no access point source is currently in use, all APs in geocoder are programmatically generated this way.

Positioning a more suitable access point would require either specific point locations from a data supplier or an enhancement to the process that takes into account parcel polygons.  The point of closest parcel approach to the named segment could provide a possible location, or perhaps range of location candidates for parallel frontage.  ITN and parcel geometry would have to align well for this to work.  It would still be messy in cases of data inconsistencies or multiple sources where some do not have parcel information.

**Comment by alixcote** [comment]
In this case, we need to get more specific data from the custodian. No bug in the code, but this could be an enhancement using something like AI to use images to get better data points. Close and will create a user story in JIRA.
