### ISSUE TITLE
maxResults = 1 can produce a different top result than maxResults > 1 interpretations

### ISSUE THREAD

**Issue by gleeming** [bcgov/ols-geocoder#218]
If an input string is an exact match when maxResults=1, then for efficiency the geocoder immediately short-circuits out from any further analysis of parsing interpretations and effectively echos the result back.  So for example with 88 Ave Delta BC or 152 St Surrey BC the response is the street match precision result with no faults (score = 78).

However when maxResults>1 no short-circuiting occurs and the usual full set of parse interpretations are considered.  In the two examples above, they start with street numbers which can be interpreted as a civic address (e.g. top match 88 Delta Ave, Burnaby, BC and 152 St. Patrick St, New Westminster, BC).  These results are at a higher match precision (block) and don't have enough faults to reduce the score below the base street match score of the exact string match.  In the 152 St case, there are 9 other addresses interpretations that score higher than the identical street response result.

This difference isn't unexpected given how the geocoder is set up to operate with short-circuiting.  If this behaviour is considered an issue, an option to deal with this could be adding a new user selectable parameter to indicate how the geocoder should handle these types of cases.  One of the modes could be to either change the score of exact string matches to 100, or to never return any other interpretations in multiple result queries if exact matches are detected (basically always short-circuit)

**Comment by alixcote** [comment]
This looks similar to #387. Closing.

**Comment by cmhodgson** [comment]
This has nothing to do with #387 and is instead indicative of a problem the geocoder has with scoring in general, that is, differentiating between "match precision" eg. locality, vs street, vs civic number, and match "accuracy" which is based on the number of faults or differences between the matched location and the input query address. It is likely that clients do not notice this problem because they either always use maxResults = 1, OR they always use maxResults >1, based on their use case. 
We will definitely need to address this problem at some point, though it may not need its own ticket as it is embedded in various other issues the geocoder has.
