### ISSUE TITLE
When street type is missing, presence of locality garbage causes geocoder to take civic number as a numbered street

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#226]
In the example below, which is missing the street type, the geocoder seems to take the street name as part of the locality garbage. Then it takes the civic number to mean a numbered street.
Example:
addressString: 213 7 WEST HASTINGS BACKPACKERS INN, VANCOUVER, BC 
Geocoder result: 213 Seventh St, New Westminster, BC
Score: 90

If BACKPACKERS INN is removed, Geocoder standardizes to W Hastings.
If the street type is added, Geocoder standardizes to W Hastings.

**Comment by cmhodgson** [comment]
Note that the correct answer of unit 213 - 7 WEST HASTINGS St, VANCOUVER, BC has the same score of 90. The trade-off is between a 1 point locality alias fault and a 1 point unit number notmatched fault - maybe the locality alias should cost more than the unknown unit number?
Part of the problem here is that there is no additional cost to taking out more garbage. This is both the power and the weakness of  a fixed penalty for garbage. Perhaps a sub-point penalty (like a tenth of a point) which could be invisible to users but affects the sort order so that a result with the same score but less garbage words comes first? (scores a few tenths of a point higher)

**Comment by BK01** [comment]
Closing. Added example to AI documentation.
