### ISSUE TITLE
Add support for a Locality Point exception list

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#262]
Some DRA locality centroids and BCGIS locality points are too far away from their localities to allow you to use them as route origin or destination points. Watson Lake is a good example:

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/da89c3f0-94f0-427a-a478-bed021c98d88)

We need to be able to define a list of locality point exceptions that are well-positioned with the populated place to be used as route origin or destination points, and locality-level match locations. The data prep scripts must be enhanced to have this list take precedence over matching DRA centroids and BCGNIS populated place points.

We can use the locality point exception list to update incorrect locality locations as soon as we detect them instead of having to wait for data custodians to correct their source data. We can provide data custodians with this file to allow them to update their source data when it is convenient for them.

QA note: If the location of a given localityName is not actually within the extent of the provided draLocalityName, the localityName should be rejected.

OnRoute needs these accurate out-of-province points so that carriers can create routes starting or ending in localities in adjacent jurisdictions.

MoH, MCFD, Vital Stats, and all others who have lots of PO BOX addresses in their data and rely on an accurate locality point to correctly determine administrative area require this enhancement.

**Comment by gleeming** [comment]
I've made the changes in FME and it currently runs using a test file I created.  To make the overall process work better, I changed the input file schema to the following:

|Field Name |Description|
|--|--|
localityName| Locality name. If locality is in BC, name should be an official populated place or IR name in BCGNIS
sourceType| either ITN or BCGNIS
province|province, territory, or state code
lat| Latitude
lon| Longitude

Since BCGNIS doesn't have a primary key, and in some cases (like 105 Mile House) we actually want to move it to a different ITN locality, this approach works better.  It still matches on name, but for multiple BCGNIS cases it will choose the closest record to the proposed new point location.

The script is set up to reject bad inputs to the existing QA file, and for now has a 15km maximum tolerance set for moving any point.

**Comment by brad-sparks-gov-bc-ca** [comment]
Thanks Graeme - I have added an "OOPR correction" to the locality-locations.csv file for Watson Lake, YT using coordinates 60.0628,-128.7109
After the next data refresh for the Geocoder should correctly place Watson Lake, YT.
Next data refresh should be within the next month...

**Comment by BK01** [comment]
Closing. Validated that the locality-locations.csv file is working to update locality locations.
