### ISSUE TITLE
Add support for hwy and freeway exits as intersections

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#6]
Highway and freeway exits should be recognized as a type of intersection by the geocoder and route planner since they are part of the road network. 
BC Wildfire Service Fire Reporting Centre needs to be able to find a location by hwy exit number.

There are a couple of ways to do this:

  1. Extend ITN data prep to create the appropriate exit street aliases.
  2. Extend the definition of Intersection to support exits.

Option 1 seems simpler at this point.

1. In ITN data prep, create street aliases for off-ramps in the following form:

       Hwy <routeNo> and Exit <exitNo>

Here's an example:

            Hwy 1 and Exit 305

This form doesn't distinguish between the two directions of travel (e.g., NorthBound/ SouthBound) This would require an addition <direction> as in:

                   Hwy <routeNo> and Exit <exitNo> <direction>

 and here's another example:

                   Hwy 1 and Exit 305 Eastbound

With this intersection format you can enter:

                    Hwy 1 and exit 305

and the geocoder in autocompletion mode should return:

                    Hwy 1 and Exit 305 Eastbound
                    Hwy 1 and Exit 305 Westbound

**Comment by cmhodgson** [comment]
I think a slight clarification is required, for (1) the street alias is not "Hwy <routeNo> and Exit <exitNo>" but simply "Exit <exitNo>", and this alias is applied to all segments of the offramp/exit. The result of this is that you can search for an intersection using the string "Hwy <routeNo> and Exit <exitNo>" because of the "Exit <exitNo>" alias on the street segments.

**Comment by cmhodgson** [comment]
For now we will only add the exit <#> alias to the exit segment. We will not worry about the <direction>-bound or "to wherever" part of this problem at this time.

**Comment by mraross** [comment]
So assuming hwy 1 has an exit 305, please confirm after this enhancement, the geocoder will be able to match the following intersection:

    HWY 1 and Exit 305 

It should actually return more than one match since there are eastbound and westbound exit 305s.

**Comment by gleeming** [comment]
While there is no exit 305 in BC, for exit 366 in Kamloops at Copperhead Dr, yes there should be two Hwy 1 and Exit 366 intersection points generated with this enhancement.

Quality of data will be based on what is in ITN.  There will likely be a few segments that need updating to add or remove exit attribution in order to fix issues.

**Comment by mraross** [comment]
Verified in v4.1 gold in Test using  Hwy 1 and Exit 366.
