### ISSUE TITLE
Deploy a second batch geocoder to support continuous availability

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#65]
By deploying a second batch geocoder on its own CPF, we get continuous availability.

**Comment by cmhodgson** [comment]
I believe this is more complex that you may think... I don't think it is possible to put a load balancer in front of the CPFs because we would need a way to ensure requests such as status updates and download requests are routed to the correct instance of CPF... perhaps with a smart enough load balancer this could be done, but it would have to inspect the returned packets for job ids and keep a database of which job id goes to which CPF instance... and then if the CPF that was running your job goes down you have to know to restart your job when you fail to get a status update. This would also require that the 2 CPFs had non-overlapping job ids. Really, isn't the CPF front end already basically a state-aware load balancer, with the backend cpf workers providing the continuous availability?

**Comment by alixcote** [comment]
Closing. Moving to OpenShift with failover will address this.
