### ISSUE TITLE
Missing truck route at bridle falls

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#71]
55270 Chilliwack Bench FSR, Chilliwack River Valley, BC
6155 Rockwell Dr, Agassiz, BC

Bridal Falls Offramp Rd EastBound not classified as truck route sending trucks the long way around to get to Agassiz

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/f8dd5467-5a1e-4af5-a575-6e9a55f0393e)

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/537f57e3-932f-45e7-b9ac-027a8e300355)

**Comment by gleeming** [comment]
This should be moved to router issues.

There are lots of "missing" cases like this at highway on/offramps.  We have not been updating them because I don't know what the local truck bylaws state for these cases. We have also been concerned that there may be some ramps that are deliberately excluded from the truck layer.  These could be cases with steep/tight curves or have banks that could be problematic for trucks with tall loads.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-router #225](https://github.com/bcgov/ols-router/issues/225) via [**ZenHub**](https://www.zenhub.com/)
