### ISSUE TITLE
Unusual occupant and site names 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#73]
Some sites with civic addresses have site names that match their occupant name. This should only happen when a site has a non-civic address.

**Comment by mraross** [comment]
This is really odd: a civic address with a site name and an occupant name and the occupant name is different:

UNIT 205 Honour Secondary School -- 14727 108 Ave, Surrey, BC
Honour Secondary School ** UNIT 205 Honour Secondary School -- 14727 108 Ave, Surrey, BC

**Comment by mraross** [comment]
Cache Creek Elementary -- 1260 Hwy 97, Cache Creek, BC

is both a site name and an occupant name

**Comment by mraross** [comment]
Woodland Centre School -- 7360 Hwy 16 E, Vanderhoof, BC
Woodland Centre School ** 7360 Hwy 16 E, Vanderhoof, BC

**Comment by mraross** [comment]
UNIT 618 iLearn DL Secondary School -- 7184 120 St, Surrey, BC
iLearn DL Secondary School ** UNIT 618 iLearn DL Secondary School -- 7184 120 St, Surrey, BC

**Comment by mraross** [comment]
UNIT 268 Maple Hill School -- 8131 Westminster Hwy, Richmond, BC
Maple Hill School ** UNIT 268 Maple Hill School -- 8131 Westminster Hwy, Richmond, BC

**Comment by mraross** [comment]
First Nations Consulting Services -- 16120 8 Ave, Surrey, BC
First Nations Consulting Services ** 16120 8 Ave, Surrey, BC

**Comment by cmhodgson** [comment]
The cases of the unit having a site name are different because they are technically 2nd level sites. If Maple Hill School is located in UNIT 268 - 8131 Westminster Hwy, Richmond, BC, then Maple Hill School is not the site name of 8131 Westminster Hwy, Richmond, BC, but of that particular unit. There is no site name for 8131 Westminster Hwy, Richmond, BC. I'm not sure how these are getting stored but I'm not sure it is the intended way, or perhaps we need to review the intended input/output for these kinds of sites.

I'm not sure why there is a problem with a site name and an occupant name being the same on a civic address? I believe this is expected and allowed? Schools being the primary example of such.

**Comment by mraross** [comment]
If the site name came from AddressBC, that's fine but if an occupant name ended up in the site name of a civic address, that's bad because occupant data authorities don't have authority over civic addresses. For example, if Chris' Head Shop located at 1175 Douglas St, Victoria, BC got assigned to the site name of same civic address through GSR import, then everyone would see Chris' Head Shop in the matching civic address. CIBC might have a quibble with that. Only non-civic addresses should be assigned a site name during GSR import.

**Comment by cmhodgson** [comment]
Graeme, I think the last sentence of Michael's last comment may not be true of what we are currently doing, in light of the earlier examples, can you comment? I guess it is possible that the geocoder is making up the site names but I think I get them from your process. I didn't know that civic addresses weren't supposed to have site names like this.

**Comment by gleeming** [comment]
There is already partly working logic in the site prep script to remove site names from GSR CAPs.  However it looks like this is only being applied to cases where the civic address was also in other sources, and not when it was a GSR-only address.  In the ResultPrep custom tranformer, the NotMatched output from the ResultMatcher factory should be redirected into the GSRtester factory.

**Comment by gleeming** [comment]
I made an FME script change to remove the site name for GSR CAPs.  NCAPs still need both a site name and an occupant name since the GSR address is an unstructured string, and this is the only efficient way in the current data processing stream to link the occupant record to the previously generated occupant record.  This could perhaps be cleaned up in the future with a Java-based processing pipeline.

**Comment by mraross** [comment]
Verified in v4.1 gold in Test
