### ISSUE TITLE
Treat postal elements found out of context as postal-element-not-allowed faults instead of unrecognized-word faults

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#82]
The MSP address file has 29 addresses containing the abbreviation "GD" for General Delivery.

The Geocoder deducts a penalty of 33 points (UNRECOGNIZED.notAllowed).

Since this is a valid Canada Post abbreviation, could it be added to the Geocoder known vocabulary, similar to PO Box? And the penalty could be reduced similar to PO Box, which only gets a 1 point deduction?

Example:
2104 CYPRESS ST GD, THORNHILL, BC

**Comment by mraross** [comment]
GD is part of the geocoder's known vocabulary but only recognized as such in a valid postal address context such as:

    GD STN A, Victoria, BC

The example you found:

  2104 CYPRESS ST GD, THORNHILL, BC

is an invalid postal address since there is a civic number and street name which contradicts the GD.

To revise the suggestion slightly: Treat known postal elements that are found out of context as a postal element not allowed fault instead of an unrecognized word fault.

**Comment by cmhodgson** [comment]
This is another addition to the "smarten up the unrecognized logic" concept.

**Comment by cmhodgson** [comment]
GD previously had to come before STN <#> ... "GENERAL DELIVERY" was valid anywhere. I've now removed the optional GD from the <POSTAL>? STN, and added it as an alternative to "GENERAL DELIVERY", recognized anywhere in the input.

**Comment by cmhodgson** [comment]
Moved from a comment in an unrelated ticket:
> 9695 PREST RD , postal stn CHILLIWACK, BC => postalelement.notAllowed and locality.missing
> 9695 PREST RD , postal station CHILLIWACK, BC => postalelement.notAllowed
> 
> need to handle postal stn. Can we use an abbreviation such as stn=>station?

The actual problem here is that the "postal stn" pattern expects the following word to be the name or number of the postal station, and so it eats chilliwack - "Postal station chiliwack". Secondarily, "postal station" is not accepted as a postal junk term at all, and there fault listed above seems to be incorrect, as I get an unrecognized.notallowed fault, as the new back alley garbage handling eats up the "postal station" just fine. 

Should postal stn NOT require a follow-up word? Should we chuck it entirely and let the back alley handle it? Should we add station as an alternative to stn in the postal junk handling? An abbreviation will not handle it as the postal junk handling is done very early using regex's, before we apply any abbreviations.

**Comment by alixcote** [comment]
This is resolved. 2104 CYPRESS ST GD, THORNHILL, BC gives a score of 99.
