### ISSUE TITLE
Soften penalty for missing ampersand character

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#84]
The MSP address reject file has 34 addresses with a missing "&" in the road name. E.g.:
189 ROD GUN RD, COURTENAY, BC
The correct address is 189 ROD & GUN RD, COURTENAY, BC

The faults assigned by the geocoder are: 
[UNRECOGNIZED.notAllowed:33, STREET_NAME.partialMatch:1]

Could the Geocoder soften the punishment for this missing character since it is able to identify the correct address?

**Comment by cmhodgson** [comment]
The trick is, we don't know it is able to identify the correct address, because the street name is not correct. I think the street name logic doesn't currently allow for out-of-order or missing-middle-part, situations, so the "ROD" is interpreted as the street name (missing some parts) and "GUN" is an extra word that doesn't make any sense. Possibly could be handled by similar logic as the extra "S" character in the missing apostrophe case.

**Comment by alixcote** [comment]
Giving a score of 90 now when the & is missing from the street address. 34 examples. Closing for now until further issues come up.
